export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PASSWORD_RESET_FORM_HIDDEN_FIELDS =
  "PASSWORD_RESET_FORM_HIDDEN_FIELDS";
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_SUB_COLLECTIONS = "GET_SUB_COLLECTIONS";
export const GET_PRODUCTS = "GET_PRODUCTS";
